Portfolio project: Setup and mobile version skeleton
hamzaw9/my-portfolio pull request #1
Opened 2023-05-03 19:49 UTC by hamzaw9

This project aims to create an appealing portfolio to showcase my projects/skills. 
But for now, this project contains only 2 sections:

- Header Section (Logo & navbar)

- Main Section (Main text & social media links)

2023-05-03 20:10 UTC, hiromataba requested changes
Hi @hamzaw9   :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/160092588-b3f37e8e-a1d9-4b14-84fc-7ec1fed7b3e5.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your PR has a proper title and description  :+1: 
- Your linters are passing :heavy_check_mark:  
- Profesional README file :rocket: 

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 20:10 UTC, hiromataba commented on index.html
> +        <i class="fa-solid fa-bars"></i>
- [ ] The hamburger button should have  a nav tag, the nav tag is for semantics reason, and the right position for convention and user experience for mobile devices

2023-05-03 20:10 UTC, hiromataba commented on index.html
> +      </main>
- You should use the `section` tag to wrap this section actually , It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info

2023-05-03 20:10 UTC, hiromataba commented on index.html
> +        <h2>I’m Hamza Baig. Glad to see <br> you!</h2>
- [ ] Your main title should be a h1 tag, If you want that google (and other search engines) knows about a specific topic, in this case, you, use an h1 tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info

2023-05-03 20:10 UTC, hiromataba commented on index.html
> +          <a href="#"><img src="images/peace icon.svg" alt="Peace icon"></a>
- [ ]  The list of icons should  use a `ul` tag to group them, and `li` per icon; each icon has `a` link (a tag).
Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href.

2023-05-04 01:58 UTC, hamzaw9 commented
**Incorporate reviewer feedback: update index.html and style.css files to improve accessibility and layout.**

2023-05-04 02:19 UTC, taldr27 approved these changes
# Status: Approved! 🟢 
Hi @hamzaw9, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉

![congrats](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

## Highlights 🎉 🎯💯🙌👍🤓
✅ Professional and customized README. 
✅ Linters tests passing.
✅ Correct use of GitHub Flow.
✅ Incorporates feedback from previous code reviews.
✅ Pull request has a descriptive title and summary.

## Optional suggestions 💭

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-05-04 02:19 UTC, taldr27 commented on index.html
> +      </section>
Great work incorporating the suggestions from the previous reviewer! I do **have a few optional suggestions that could make your project look even better and more closely match** the [Figma template provided](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0-1&t=NcRw8dFhHkmW6sux-0):

- [ ] **[OPTIONAL]** Would you mind checking the `padding` you added to your `wrapper`? You could remove it from there and instead apply `padding` **for each section separately**. For example, you could add some `padding` for the `header` and some `padding` for your section. This small adjustment will help your **background look more similar to the template**. 😉

  ### Your design:
  ![image](https://user-images.githubusercontent.com/107952724/236096285-8b05a199-f82a-40dc-be96-9bc9e317daa6.png)

  ### Figma design:
  ![image](https://user-images.githubusercontent.com/107952724/236096354-3a2bbe3f-3b93-447d-891d-1b29200bead9.png)

- [ ] **[OPTIONAL]** Additionally, you could try adding `align-items: center` to center the medium icon. This **will help make the design more visually appealing and professional**. 🎯

  ![image](https://user-images.githubusercontent.com/107952724/236096665-1460680b-aa11-45dc-8b82-8ab14500aae1.png)

2023-05-04 04:33 UTC, merged